create table person
(
    id          integer generated by default as identity
        constraint person_pk
            primary key,
    fullname    varchar not null,
    birthofyear integer not null
);

create table book
(
    id       integer generated by default as identity
        constraint book_pk
            primary key,
    name     varchar not null,
    author   varchar not null,
    year     integer not null,
    personid integer
        constraint book_personid_fk
            references person on delete set null
);




